services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - techchallenge
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: techchallenge_db
      POSTGRES_USER: tc_user
      POSTGRES_PASSWORD: tc_password
    networks:
      - techchallenge
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

networks:
  techchallenge: