# Generated by Django 4.2 on 2025-05-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.PositiveIntegerField()),
                ('num2', models.PositiveIntegerField()),
                ('num3', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=20)),
                ('media', models.PositiveIntegerField()),
                ('mediana', models.PositiveIntegerField()),
            ],
        ),
    ]
