# Generated by Django 4.2.11 on 2025-05-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processamento',
            name='media',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processamento',
            name='mediana',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processamento',
            name='status',
            field=models.CharField(default='Processando', max_length=20),
        ),
    ]
