# Generated by Django 4.2.11 on 2025-05-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_alter_processamento_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processamento',
            name='media',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processamento',
            name='mediana',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processamento',
            name='num1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='processamento',
            name='num2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='processamento',
            name='num3',
            field=models.FloatField(),
        ),
    ]
